<form id="reset-password-save" action="/profile/resetPost?k=<?php echo $this->key?>" class="ui form" method="post">
    <div class="field">
        <label for="new_pass">New Password</label>
        <input type="password" name="pass_confirmation" id="new_pass" data-validation="length" value="" data-validation-length="min1">
    </div>
    <div class="field">
        <label for="password">Confirm Password</label>
        <input type="password" name="pass" id="new_pass_confirm" value="" data-validation="length confirmation" data-validation-length="min1" >
    </div>
    <button class="ui button" data-action="resetSaveAction" type="submit">Change Password</button>
</form>