<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Please Sign In</h3>
            </div>
            <div class="panel-body">
                <form role="form" action="<?php echo $this->url('admin', array('action' => 'authenticate')) ?>" method="post">
                    <fieldset>
                        <div class="form-group">
                            <input class="form-control" placeholder="Login" name="login" type="text" autofocus="">
                        </div>
                        <div class="form-group">
                            <input class="form-control" placeholder="Password" name="password" type="password" value="">
                        </div>
                        <div class="checkbox">
                            <label>
                                <input name="remember" type="checkbox" value="1">Remember Me
                            </label>
                        </div>
                        <!-- Change this to a button or input when using this as a form -->
                        <button type="submit" class="btn btn-lg btn-success btn-block">Login</button>
                    </fieldset>
                </form>
            </div>
        </div>
        <br>
        <?php if ($this->messages): ?>
            <?php foreach($this->messages as $message): ?>
                <div class="alert alert-success" role="alert">
                    <?php echo $message ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>